name: meald
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  http: ^1.2.2
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.2
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mealdLogo.gif
    - assets/Driver.gif
    - assets/Location.gif
    - assets/logo.gif
    - assets/LOGO.png
    - assets/mealdLogo.jpg
    - assets/User.gif
    - assets/addpic.png
    - assets/profileBG.jpg
    - assets/home.png
    - assets/list.png
    - assets/add.png
    - assets/notif.png
    - assets/profile.png
    - assets/test.png
    - assets/userlogo.png
